### PR TITLE
src/pz.link.m: fix typo "too modules" -> "two ..." (also in tests)

### PR DESCRIPTION
**Pull request by srenatus**
Trivial fix, doesn't warrant adding a line added to AUTHORS, I'd think. What do you think?

### CODE REVIEW

**Review by PaulBone — APPROVED** [review]
Thanks for spotting that.

**Comment by PaulBone** [comment]
It's probably not necessary.  While it's nice to credit people for their work, the reason I want to keep the AUTHORS file is for everyone's legal protection.  If I ever want to change the License of Plasma (not that I'm planning, but imagine some case happens that finds a problem with the MIT license) then I need the permission of all the copyright owners. That's easy to find if there's an AUTHORS file.  So for such a trivial change you're probably fine with me making these kinds of relicensing decisions (if it ever comes up), but I have to ask otherwise it leaves me in a vulenrable position if I change the license in the future.  Does this make sense? Are you still okay with this?

I'll update CONTRIBUTING.md for others in the future.

**Comment by srenatus** [comment]
#288 looks alright to me and I agree with it for this small change. Thanks for clarifying!

**Comment by PaulBone** [comment]
No worries, thanks for the feedback!

**Pull request merged**
