### PR TITLE
[build] Make mtags and ctags optional dependencies

### PR DESCRIPTION
**Pull request by sullyj3**
See #59

### CODE REVIEW

**Comment by PaulBone** [comment]
Thanks for your interest.  I like the graceful degredation here.  However:
 * We should probably remove tags from being a dependency on all.
 * The user should see an error message if they _do_ run 'make tags'.

**Comment by sullyj3** [comment]
Oh, sure, ok. Do you not use "make tags"? Do you run both commands manually?

**Comment by PaulBone** [comment]
Sometimes I don't use "make tags" but I should, it shouldn't be in "make all".  So contrary to what I wrote last night (sorry I was tired) I think just simply removing tags from all is best, and not making any other change (since bash will tell you when a command is missing anyway).

**Comment by PaulBone** [comment]
Closing this in favour of b55fc381903805f1a02d2ae5e04a6e116170f784

**Comment by PaulBone** [comment]
I appreciate the PR and even though it didn't work out this time, I hope you'll hang around and I look forward to future contributions.

BTW do I know you from somewhere? some place online or IRL?  Your name is familiar.

**Comment by PaulBone** [comment]
Cool, hope you enjoyed ti, There won't be one this week because I'm traveling. and I'm not sure about next week yet.

**Pull request closed without merging**
