### PR TITLE
Don't use abort() to report that command line arguments are unsupported

### PR DESCRIPTION
**Pull request by PaulBone**

### CODE REVIEW

**Comment by PaulBone** [comment]
Hi @Ivo-Balbaert,

Can you verify that this fixes the test failure you saw on WSL?  Thanks.

**Comment by Ivo-Balbaert** [comment]
Hi Paul. I did a git pull, then a make and make test. The result is still:

ivo@DESKTOP-KN14QQK:~/plasma$ make test
(cd tests; ./run_tests.sh dev)
.........................................................................................................................................*.....................
158 out of 159 passed, 1 failed
Failing tests:
        missing/args
make: *** [Makefile:172: test] Error 1

**Comment by PaulBone** [comment]
Are you on the bug335 branch? I didn't merge it yet.
```
$ git checkout -b bug335 origin/bug335
```

If you are already leave it with me, I'll try to reproduce it myself.  Which distro did you choose in WSL?

Thanks.

**Comment by Ivo-Balbaert** [comment]
I am not on that bug335 branch Paul. I ran Ubuntu 20.04 LTS under WSL2, downloaded from Microsoft Store.

**Comment by PaulBone** [comment]
> I am not on that bug335 branch Paul. I ran Ubuntu 20.04 LTS under WSL2, downloaded from Microsoft Store.

I'm sorry I didn't read clearly in https://github.com/PlasmaLang/plasma/issues/298#issuecomment-801196197 that you gave the version numbers there. I'll test this since I'm pretty sure that branch fixes it.

**Pull request merged**
